[BE] 프로젝트 리뷰 요청
codesquad-member-2020/dust-11 pull request #45
Opened 2020-04-04 13:55 UTC by 102092

### 구현사항
- 읍면동을 통한 미세먼지 현황 조회
- 위도,경도를 통한 읍면동 반환
- 날짜를 통해 대기질 예보현황 조회
- heroku, aws 배포

### 미구현사항
- 에러처리
- batch 작업
- 리팩토링... 

### 질문사항
- 현재 브런치에, 다른 팀원의 커밋이 섞여있습니다. 죄송합니다 ㅠㅠ 이 부분을 rebase등을 이용하여 깨끗하게 만들고 싶었으나, 어려워서 해당 부분을 해결하지 못하고, 풀리퀘를 보내게 되었습니다.  혹시 이런상황에서는 어떤 방법을 이용하는 지 힌트를 주신다면 공부해보도록 하겠습니다.

- 선택사항이었던 batch를 해보진 못했습니다. 무분별한 API 요청 줄이기 위하여 사용하는 듯 한데, 미세먼지 프로젝트에는 어떤 부분에 어떻게 배치 작업을 할당할 수 있을까요?

확실히, 성급한 구현보다는 팀원과의 소통 그리고 프로젝트 분석에 시간을 좀 더 쏟아야함을 느꼈습니다.
이를 기반으로 다음 프로젝트에는 좀 더 짜임새있는 시간을 가져보고 싶습니다.
한 주간 신경써주셔서 감사합니다!

2020-04-05 04:04 UTC, wheejuni requested changes
BE 리뷰 완료했습니다! 수고 많으셨어요.
코멘트 참고해주시고 질문 있으시면 댓글 남겨주세요.

2020-04-05 05:57 UTC, 102092 commented on Web/BE/src/main/java/com/dust11/han/HanApplication.java
> +public class HanApplication {
ㅎㅎ 다음번에는 좀 더 신경써서 짓겠습니다

2020-04-06 14:07 UTC, 102092 commented on Web/BE/src/main/java/com/dust11/han/controller/GeneralExceptionHandler.java
> +  public ResponseEntity<?> WrongEncode(EncodingException e) {
어이구..ㅠㅠ

2020-04-06 14:10 UTC, 102092 commented on Web/BE/src/main/java/com/dust11/han/controller/LocationController.java
> +        .getAsJsonObject().get("region_3depth_name").getAsString();
@wheejuni 서로 다른 API와 통신하기 때문에, 새로운 서비스 객체를 통해 기능을 분리하고 코드를 간결화 한다고 생각하면 될까요?

2020-04-06 14:15 UTC, 102092 commented on Web/BE/src/main/java/com/dust11/han/error/EncodingException.java
> +public class EncodingException extends IOException {
@wheejuni checked exception 반드시 처리해줘야하는 걸로만 알고 있습니다. 혹시 말씀하신 항상 주의해야하는 이유에 대해 좀 더 알 수 있을까요?

2020-04-06 14:26 UTC, 102092 commented on Web/BE/src/main/java/com/dust11/han/model/UrlRequest.java
> +public class UrlRequest {
@wheejuni 각 요청별로 객체를 만들고, 이를 bean으로 등록하여 service 에서 주입받아서 사용하는게 어떨까라는 막연한 생각에 객체로 설계하게 되었습니다.

2020-04-06 14:29 UTC, 102092 commented on Web/BE/src/main/java/com/dust11/han/controller/GeneralExceptionHandler.java
> +  private ResponseEntity<ApiResult> newResponse(Throwable throwable, HttpStatus status) {
감사합니다. 새로운 사실을 알았네요!

2020-04-22 06:41 UTC, honux77 commented on Web/BE/src/main/java/com/dust11/han/HanApplication.java
> +public class HanApplication {
한어플 좋은데요 ㅋㅋㅋ

2020-04-22 06:45 UTC, merged